In [1]:
import pandas as pd
import glob, os, time
import helper

In [2]:
helper.clean_niti_data('./CSV/')

Processed 13 files in 1.9123339653015137 seconds

In [3]:
files = glob.glob('./PROCESSED/*.csv')

In [4]:
datas = [pd.read_csv(file) for file in files]

In [9]:
datas[12].tail()

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16
27,Uttarakhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3226.0,3726.0,4190.0,5620.0,5950.0,7380.0,7970.0,9380.0,15340.0,15200.0
28,West Bengal,592.0,691.0,843.0,856.0,1115.0,1202.0,1500.0,1652.0,1852.0,...,13142.0,16192.0,19470.0,27700.0,30560.0,35610.0,40100.0,45580.0,59220.0,62630.0
29,All States,6755.0,7656.0,9352.0,10788.0,12418.0,17031.0,19609.0,22651.0,25998.0,...,222988.0,265466.0,331540.0,392940.0,451940.0,523570.0,602940.0,679200.0,982150.0,1049780.0
30,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5139.0,7353.0,8920.0,10510.0,10810.0,13210.0,14570.0,15430.0,17780.0,22230.0
31,Puducherry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,800.0,927.0,1060.0,1370.0,1560.0,1720.0,1410.0,1870.0,2330.0,2730.0

In [14]:
files = glob.glob('./PROCESSED/*.csv')
files

['./PROCESSED/Interest_Payments.csv',
 './PROCESSED/Aggregate_Expenditure.csv',
 './PROCESSED/Aggregate_Receipts.csv',
 './PROCESSED/Capital_Expenditure.csv',
 './PROCESSED/Capital_Receipts.csv',
 './PROCESSED/Fiscal_Deficits.csv',
 './PROCESSED/Nominal_GSDP_Series.csv',
 './PROCESSED/Outstanding_Liabilities.csv',
 './PROCESSED/Own_Tax_Revenues.csv',
 './PROCESSED/Revenue_Deficits.csv',
 './PROCESSED/Revenue_Expenditure.csv',
 './PROCESSED/Revenue_Receipts.csv',
 './PROCESSED/Social_Sector_Expenditure.csv']

In [15]:
feature_files = ['./PROCESSED/Capital_Receipts.csv',
 './PROCESSED/Aggregate_Receipts.csv',
 './PROCESSED/Social_Sector_Expenditure.csv',
 './PROCESSED/Interest_Payments.csv',
 './PROCESSED/Own_Tax_Revenues.csv',
 './PROCESSED/Fiscal_Deficits.csv',
 './PROCESSED/Outstanding_Liabilities.csv',
 './PROCESSED/Aggregate_Expenditure.csv',
 './PROCESSED/Revenue_Receipts.csv',
 './PROCESSED/Revenue_Expenditure.csv',
 './PROCESSED/Revenue_Deficits.csv',
 './PROCESSED/Capital_Expenditure.csv']

In [101]:
finalDF = pd.DataFrame()
for file in feature_files:
    colname = os.path.splitext(os.path.basename(file))[0]
    
    mydata = pd.read_csv(file)
    series = pd.Series([],dtype=pd.StringDtype()) 
    for row in mydata.iloc[:1,1:].values:
        series = series.append(pd.Series(row), ignore_index=True)
    finalDF[colname] = series

In [104]:
finalDF.head()

,Capital_Receipts,Aggregate_Receipts,Social_Sector_Expenditure,Interest_Payments,Own_Tax_Revenues,Fiscal_Deficits,Outstanding_Liabilities,Aggregate_Expenditure,Revenue_Receipts,Revenue_Expenditure,Revenue_Deficits,Capital_Expenditure
0,325.0,1590.0,532.0,81.7,582.0,222.1,81.50,1610.0,1265.0,1161.0,-104.0,449.0
1,323.0,1789.0,613.0,96.8,703.0,243.7,94.54,1831.0,1466.0,1386.0,-80.0,445.0
2,304.0,1943.0,697.0,112.1,808.0,172.4,110.63,1933.0,1639.0,1507.0,-132.6,427.0
3,546.0,2499.0,1073.0,123.0,965.0,493.0,129.40,2588.0,1953.0,2042.0,88.6,546.0
4,668.0,2962.0,1193.0,153.8,1174.0,591.4,152.24,3119.0,2294.0,2463.0,169.0,656.0

In [91]:
mydata.iloc[:1,1:].values

array([[  449.  ,   445.  ,   427.  ,   546.  ,   656.  ,   633.  ,
          824.  ,   853.  ,   977.  ,  1053.  ,  1076.  ,  1306.  ,
         1793.  ,  2523.  ,  2945.  ,  3687.  ,  1872.  ,  3201.  ,
         5014.  ,  4729.  ,  5049.  ,  6348.  ,  8316.  , 10290.  ,
        15845.  , 13391.  , 15210.  , 20892.  , 18949.67, 21626.86,
        22101.38, 25466.19, 26738.54, 26254.78, 12758.83, 14624.21,
             nan]])

In [130]:
ind = pd.Series([],dtype=pd.StringDtype()) 
for i in mydata.T.index:
    ind = ind.append(pd.Series(i), ignore_index=True)
ind

years = list(map(lambda str: str.split('-')[0], ind.values))

In [131]:
years

['State',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016']

In [133]:
years.remove('State')

In [151]:
len(years)

37

In [143]:
df = pd.DataFrame(finalDF)

In [144]:
df

,Capital_Receipts,Aggregate_Receipts,Social_Sector_Expenditure,Interest_Payments,Own_Tax_Revenues,Fiscal_Deficits,Outstanding_Liabilities,Aggregate_Expenditure,Revenue_Receipts,Revenue_Expenditure,Revenue_Deficits,Capital_Expenditure
0,325.00,1590.00,532.0,81.7000,582.0,222.1,81.50,1610.00,1265.00,1161.00,-104.0,449.00
1,323.00,1789.00,613.0,96.8000,703.0,243.7,94.54,1831.00,1466.00,1386.00,-80.0,445.00
2,304.00,1943.00,697.0,112.1000,808.0,172.4,110.63,1933.00,1639.00,1507.00,-132.6,427.00
3,546.00,2499.00,1073.0,123.0000,965.0,493.0,129.40,2588.00,1953.00,2042.00,88.6,546.00
4,668.00,2962.00,1193.0,153.8000,1174.0,591.4,152.24,3119.00,2294.00,2463.00,169.0,656.00
5,773.00,3546.00,1470.0,190.7000,1439.0,435.0,177.78,3413.00,2773.00,2781.00,7.3,633.00
6,906.00,3962.00,1849.0,295.6000,1559.0,804.0,202.01,4068.00,3056.00,3245.00,189.0,824.00
7,917.00,4395.00,1884.0,312.9000,1819.0,568.0,233.13,4294.00,3478.00,3441.00,-37.0,853.00
8,1005.00,5284.00,2103.0,372.8000,2122.0,673.0,283.01,5223.00,4279.00,4246.00,-33.0,977.00
9,1237.00,5714.00,2387.0,470.9000,2384.0,972.0,348.29,5768.00,4477.00,4715.00,238.2,1053.00
10,1261.00,6608.00,2741.0,590.0000,2650.0,967.1,418.09,6581.00,5347.00,5505.00,157.6,1076.00
11,1567.00,7849.00,3121.0,700.0000,3060.0,1125.3,486.37,7758.00,6282.00,6452.00,169.6,1306.00
12,1937.00,9003.00,3662.0,830.0000,3390.0,1569.3,560.30,8984.00,7066.00,7190.00,123.8,1793.00
13,2553.00,10804.00,3919.0,1030.0000,3830.0,1833.2,652.51,10541.00,8251.00,8018.00,-232.3,2523.00
14,3381.00,12167.00,4265.0,1260.0000,4230.0,2348.5,754.18,12459.00,8786.00,9514.00,727.8,2945.00
15,4457.00,14332.00,5507.0,1530.0000,4120.0,2416.8,832.82,14301.00,9875.00,10614.00,738.9,3687.00
16,4457.00,15650.00,6284.0,1840.0000,4880.0,2811.5,904.56,16265.00,11193.00,14392.00,3199.1,1872.00
17,4863.00,18704.00,6759.0,2150.0000,7110.0,2427.8,998.75,17745.00,13841.00,14544.00,703.2,3201.00
18,6814.00,21074.00,8927.0,2640.0000,7960.0,5705.6,1100.54,21958.00,14260.00,16944.00,2684.1,5014.00
19,6221.00,23026.00,8831.0,3100.0000,9010.0,4976.4,1236.80,22767.00,16805.00,18038.00,1233.3,4729.00
20,8310.00,27785.00,10006.0,3790.0000,10550.0,7305.9,1395.10,28119.00,19475.00,23070.00,3595.1,5049.00
21,9732.00,31577.00,10876.0,4580.0000,12560.0,6723.1,1505.50,31074.00,21845.00,24726.00,2881.3,6348.00
22,11253.00,34256.00,11179.0,6130.0000,12620.0,7630.0,1742.60,34373.00,23003.00,26057.00,3054.0,8316.00
23,14244.00,41113.00,13367.0,6860.0000,13810.0,7450.0,1962.00,40120.00,26869.00,29830.00,2962.0,10290.00
24,19377.00,48127.00,13821.0,7090.0000,16250.0,8190.0,1226.10,47153.00,28750.00,31307.00,2558.0,15845.00
25,13454.00,48305.00,14900.0,7010.0000,19210.0,8300.0,1405.10,48306.00,34851.00,34915.00,64.0,13391.00
26,13548.00,57793.00,18654.0,7280.0000,23930.0,5640.0,1609.00,56648.00,44245.00,41438.00,-2807.0,15210.00
27,23767.00,77910.00,24471.0,7590.0000,28790.0,8790.0,NaN,74875.00,54143.00,53984.00,-159.0,20892.00
28,13781.16,76639.61,31440.0,8060.0000,33360.0,12410.0,NaN,80803.89,62858.45,61854.22,-1000.0,18949.67
29,20697.64,85375.99,30280.0,8910.0000,35180.0,14010.0,NaN,85074.79,64678.35,63447.93,-1230.0,21626.86
30,21635.67,102631.97,39130.0,9670.0000,45140.0,11800.0,NaN,100635.64,80996.30,78534.26,-2460.0,22101.38
31,21919.13,115472.82,45400.0,10560.0000,53280.0,15400.0,NaN,115881.55,93553.69,90415.36,-3140.0,25466.19
32,25725.24,129555.52,49440.0,11660.0000,59880.0,17510.0,NaN,129440.92,103830.28,102702.38,-1130.0,26738.54
33,28860.16,139578.99,53740.0,12910.0000,64120.0,18040.0,NaN,136629.27,110718.83,110374.49,-340.0,26254.78
34,36366.71,127039.16,46150.0,10007.2210,38480.0,20320.0,NaN,111067.46,90672.45,98308.63,14240.0,12758.83
35,21727.49,111108.31,52450.0,9477.8651,44420.0,17580.0,NaN,112048.99,89380.82,97424.78,7300.0,14624.21
36,24790.16,134090.01,NaN,12258.3468,NaN,NaN,NaN,NaN,109299.85,NaN,NaN,NaN

In [153]:
df.index = years

In [154]:
df

,Capital_Receipts,Aggregate_Receipts,Social_Sector_Expenditure,Interest_Payments,Own_Tax_Revenues,Fiscal_Deficits,Outstanding_Liabilities,Aggregate_Expenditure,Revenue_Receipts,Revenue_Expenditure,Revenue_Deficits,Capital_Expenditure
1980,325.00,1590.00,532.0,81.7000,582.0,222.1,81.50,1610.00,1265.00,1161.00,-104.0,449.00
1981,323.00,1789.00,613.0,96.8000,703.0,243.7,94.54,1831.00,1466.00,1386.00,-80.0,445.00
1982,304.00,1943.00,697.0,112.1000,808.0,172.4,110.63,1933.00,1639.00,1507.00,-132.6,427.00
1983,546.00,2499.00,1073.0,123.0000,965.0,493.0,129.40,2588.00,1953.00,2042.00,88.6,546.00
1984,668.00,2962.00,1193.0,153.8000,1174.0,591.4,152.24,3119.00,2294.00,2463.00,169.0,656.00
1985,773.00,3546.00,1470.0,190.7000,1439.0,435.0,177.78,3413.00,2773.00,2781.00,7.3,633.00
1986,906.00,3962.00,1849.0,295.6000,1559.0,804.0,202.01,4068.00,3056.00,3245.00,189.0,824.00
1987,917.00,4395.00,1884.0,312.9000,1819.0,568.0,233.13,4294.00,3478.00,3441.00,-37.0,853.00
1988,1005.00,5284.00,2103.0,372.8000,2122.0,673.0,283.01,5223.00,4279.00,4246.00,-33.0,977.00
1989,1237.00,5714.00,2387.0,470.9000,2384.0,972.0,348.29,5768.00,4477.00,4715.00,238.2,1053.00
1990,1261.00,6608.00,2741.0,590.0000,2650.0,967.1,418.09,6581.00,5347.00,5505.00,157.6,1076.00
1991,1567.00,7849.00,3121.0,700.0000,3060.0,1125.3,486.37,7758.00,6282.00,6452.00,169.6,1306.00
1992,1937.00,9003.00,3662.0,830.0000,3390.0,1569.3,560.30,8984.00,7066.00,7190.00,123.8,1793.00
1993,2553.00,10804.00,3919.0,1030.0000,3830.0,1833.2,652.51,10541.00,8251.00,8018.00,-232.3,2523.00
1994,3381.00,12167.00,4265.0,1260.0000,4230.0,2348.5,754.18,12459.00,8786.00,9514.00,727.8,2945.00
1995,4457.00,14332.00,5507.0,1530.0000,4120.0,2416.8,832.82,14301.00,9875.00,10614.00,738.9,3687.00
1996,4457.00,15650.00,6284.0,1840.0000,4880.0,2811.5,904.56,16265.00,11193.00,14392.00,3199.1,1872.00
1997,4863.00,18704.00,6759.0,2150.0000,7110.0,2427.8,998.75,17745.00,13841.00,14544.00,703.2,3201.00
1998,6814.00,21074.00,8927.0,2640.0000,7960.0,5705.6,1100.54,21958.00,14260.00,16944.00,2684.1,5014.00
1999,6221.00,23026.00,8831.0,3100.0000,9010.0,4976.4,1236.80,22767.00,16805.00,18038.00,1233.3,4729.00
2000,8310.00,27785.00,10006.0,3790.0000,10550.0,7305.9,1395.10,28119.00,19475.00,23070.00,3595.1,5049.00
2001,9732.00,31577.00,10876.0,4580.0000,12560.0,6723.1,1505.50,31074.00,21845.00,24726.00,2881.3,6348.00
2002,11253.00,34256.00,11179.0,6130.0000,12620.0,7630.0,1742.60,34373.00,23003.00,26057.00,3054.0,8316.00
2003,14244.00,41113.00,13367.0,6860.0000,13810.0,7450.0,1962.00,40120.00,26869.00,29830.00,2962.0,10290.00
2004,19377.00,48127.00,13821.0,7090.0000,16250.0,8190.0,1226.10,47153.00,28750.00,31307.00,2558.0,15845.00
2005,13454.00,48305.00,14900.0,7010.0000,19210.0,8300.0,1405.10,48306.00,34851.00,34915.00,64.0,13391.00
2006,13548.00,57793.00,18654.0,7280.0000,23930.0,5640.0,1609.00,56648.00,44245.00,41438.00,-2807.0,15210.00
2007,23767.00,77910.00,24471.0,7590.0000,28790.0,8790.0,NaN,74875.00,54143.00,53984.00,-159.0,20892.00
2008,13781.16,76639.61,31440.0,8060.0000,33360.0,12410.0,NaN,80803.89,62858.45,61854.22,-1000.0,18949.67
2009,20697.64,85375.99,30280.0,8910.0000,35180.0,14010.0,NaN,85074.79,64678.35,63447.93,-1230.0,21626.86
2010,21635.67,102631.97,39130.0,9670.0000,45140.0,11800.0,NaN,100635.64,80996.30,78534.26,-2460.0,22101.38
2011,21919.13,115472.82,45400.0,10560.0000,53280.0,15400.0,NaN,115881.55,93553.69,90415.36,-3140.0,25466.19
2012,25725.24,129555.52,49440.0,11660.0000,59880.0,17510.0,NaN,129440.92,103830.28,102702.38,-1130.0,26738.54
2013,28860.16,139578.99,53740.0,12910.0000,64120.0,18040.0,NaN,136629.27,110718.83,110374.49,-340.0,26254.78
2014,36366.71,127039.16,46150.0,10007.2210,38480.0,20320.0,NaN,111067.46,90672.45,98308.63,14240.0,12758.83
2015,21727.49,111108.31,52450.0,9477.8651,44420.0,17580.0,NaN,112048.99,89380.82,97424.78,7300.0,14624.21
2016,24790.16,134090.01,NaN,12258.3468,NaN,NaN,NaN,NaN,109299.85,NaN,NaN,NaN

In [164]:
datas[0]['State'][0]

'Andhra Pradesh '

In [178]:
!mkdir statewise_csv

In [179]:
df.to_csv("statewise_csv/{}.csv".format(datas[0]['State'][0]), index=True)

In [180]:
pd.read_csv('statewise_csv/Andhra Pradesh .csv')

,Unnamed: 0,Capital_Receipts,Aggregate_Receipts,Social_Sector_Expenditure,Interest_Payments,Own_Tax_Revenues,Fiscal_Deficits,Outstanding_Liabilities,Aggregate_Expenditure,Revenue_Receipts,Revenue_Expenditure,Revenue_Deficits,Capital_Expenditure
0,1980,325.00,1590.00,532.0,81.7000,582.0,222.1,81.50,1610.00,1265.00,1161.00,-104.0,449.00
1,1981,323.00,1789.00,613.0,96.8000,703.0,243.7,94.54,1831.00,1466.00,1386.00,-80.0,445.00
2,1982,304.00,1943.00,697.0,112.1000,808.0,172.4,110.63,1933.00,1639.00,1507.00,-132.6,427.00
3,1983,546.00,2499.00,1073.0,123.0000,965.0,493.0,129.40,2588.00,1953.00,2042.00,88.6,546.00
4,1984,668.00,2962.00,1193.0,153.8000,1174.0,591.4,152.24,3119.00,2294.00,2463.00,169.0,656.00
5,1985,773.00,3546.00,1470.0,190.7000,1439.0,435.0,177.78,3413.00,2773.00,2781.00,7.3,633.00
6,1986,906.00,3962.00,1849.0,295.6000,1559.0,804.0,202.01,4068.00,3056.00,3245.00,189.0,824.00
7,1987,917.00,4395.00,1884.0,312.9000,1819.0,568.0,233.13,4294.00,3478.00,3441.00,-37.0,853.00
8,1988,1005.00,5284.00,2103.0,372.8000,2122.0,673.0,283.01,5223.00,4279.00,4246.00,-33.0,977.00
9,1989,1237.00,5714.00,2387.0,470.9000,2384.0,972.0,348.29,5768.00,4477.00,4715.00,238.2,1053.00
10,1990,1261.00,6608.00,2741.0,590.0000,2650.0,967.1,418.09,6581.00,5347.00,5505.00,157.6,1076.00
11,1991,1567.00,7849.00,3121.0,700.0000,3060.0,1125.3,486.37,7758.00,6282.00,6452.00,169.6,1306.00
12,1992,1937.00,9003.00,3662.0,830.0000,3390.0,1569.3,560.30,8984.00,7066.00,7190.00,123.8,1793.00
13,1993,2553.00,10804.00,3919.0,1030.0000,3830.0,1833.2,652.51,10541.00,8251.00,8018.00,-232.3,2523.00
14,1994,3381.00,12167.00,4265.0,1260.0000,4230.0,2348.5,754.18,12459.00,8786.00,9514.00,727.8,2945.00
15,1995,4457.00,14332.00,5507.0,1530.0000,4120.0,2416.8,832.82,14301.00,9875.00,10614.00,738.9,3687.00
16,1996,4457.00,15650.00,6284.0,1840.0000,4880.0,2811.5,904.56,16265.00,11193.00,14392.00,3199.1,1872.00
17,1997,4863.00,18704.00,6759.0,2150.0000,7110.0,2427.8,998.75,17745.00,13841.00,14544.00,703.2,3201.00
18,1998,6814.00,21074.00,8927.0,2640.0000,7960.0,5705.6,1100.54,21958.00,14260.00,16944.00,2684.1,5014.00
19,1999,6221.00,23026.00,8831.0,3100.0000,9010.0,4976.4,1236.80,22767.00,16805.00,18038.00,1233.3,4729.00
20,2000,8310.00,27785.00,10006.0,3790.0000,10550.0,7305.9,1395.10,28119.00,19475.00,23070.00,3595.1,5049.00
21,2001,9732.00,31577.00,10876.0,4580.0000,12560.0,6723.1,1505.50,31074.00,21845.00,24726.00,2881.3,6348.00
22,2002,11253.00,34256.00,11179.0,6130.0000,12620.0,7630.0,1742.60,34373.00,23003.00,26057.00,3054.0,8316.00
23,2003,14244.00,41113.00,13367.0,6860.0000,13810.0,7450.0,1962.00,40120.00,26869.00,29830.00,2962.0,10290.00
24,2004,19377.00,48127.00,13821.0,7090.0000,16250.0,8190.0,1226.10,47153.00,28750.00,31307.00,2558.0,15845.00
25,2005,13454.00,48305.00,14900.0,7010.0000,19210.0,8300.0,1405.10,48306.00,34851.00,34915.00,64.0,13391.00
26,2006,13548.00,57793.00,18654.0,7280.0000,23930.0,5640.0,1609.00,56648.00,44245.00,41438.00,-2807.0,15210.00
27,2007,23767.00,77910.00,24471.0,7590.0000,28790.0,8790.0,NaN,74875.00,54143.00,53984.00,-159.0,20892.00
28,2008,13781.16,76639.61,31440.0,8060.0000,33360.0,12410.0,NaN,80803.89,62858.45,61854.22,-1000.0,18949.67
29,2009,20697.64,85375.99,30280.0,8910.0000,35180.0,14010.0,NaN,85074.79,64678.35,63447.93,-1230.0,21626.86
30,2010,21635.67,102631.97,39130.0,9670.0000,45140.0,11800.0,NaN,100635.64,80996.30,78534.26,-2460.0,22101.38
31,2011,21919.13,115472.82,45400.0,10560.0000,53280.0,15400.0,NaN,115881.55,93553.69,90415.36,-3140.0,25466.19
32,2012,25725.24,129555.52,49440.0,11660.0000,59880.0,17510.0,NaN,129440.92,103830.28,102702.38,-1130.0,26738.54
33,2013,28860.16,139578.99,53740.0,12910.0000,64120.0,18040.0,NaN,136629.27,110718.83,110374.49,-340.0,26254.78
34,2014,36366.71,127039.16,46150.0,10007.2210,38480.0,20320.0,NaN,111067.46,90672.45,98308.63,14240.0,12758.83
35,2015,21727.49,111108.31,52450.0,9477.8651,44420.0,17580.0,NaN,112048.99,89380.82,97424.78,7300.0,14624.21
36,2016,24790.16,134090.01,NaN,12258.3468,NaN,NaN,NaN,NaN,109299.85,NaN,NaN,NaN